// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyBgjmuuUCCPJ_HRoF7_5HQ6Te-tk_ccM',
    appId: '1:707436643898:web:6e2c8d008d9e85404f5703',
    messagingSenderId: '707436643898',
    projectId: 'dolo-99e53',
    authDomain: 'dolo-99e53.firebaseapp.com',
    storageBucket: 'dolo-99e53.firebasestorage.app',
    measurementId: 'G-1F9FQKGDK6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB03IXvWqh-CLCgynIGafIakq2k43YOx5Q',
    appId: '1:707436643898:android:b4c069b9588018b34f5703',
    messagingSenderId: '707436643898',
    projectId: 'dolo-99e53',
    storageBucket: 'dolo-99e53.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBILQVHPgEE5zeATSymsiVBgQLmfyKoh54',
    appId: '1:707436643898:ios:b5ed8005b468d7c64f5703',
    messagingSenderId: '707436643898',
    projectId: 'dolo-99e53',
    storageBucket: 'dolo-99e53.firebasestorage.app',
    iosBundleId: 'com.example.dolo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBILQVHPgEE5zeATSymsiVBgQLmfyKoh54',
    appId: '1:707436643898:ios:b5ed8005b468d7c64f5703',
    messagingSenderId: '707436643898',
    projectId: 'dolo-99e53',
    storageBucket: 'dolo-99e53.firebasestorage.app',
    iosBundleId: 'com.example.dolo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyBgjmuuUCCPJ_HRoF7_5HQ6Te-tk_ccM',
    appId: '1:707436643898:web:d79658dfe26fce514f5703',
    messagingSenderId: '707436643898',
    projectId: 'dolo-99e53',
    authDomain: 'dolo-99e53.firebaseapp.com',
    storageBucket: 'dolo-99e53.firebasestorage.app',
    measurementId: 'G-MZCD88TNFP',
  );

}